//! Regression test against OpenSubdiv itself: every shape of OpenSubdiv's
//! regression catalogue, refined and patched by this crate, compared with
//! reference results computed by OpenSubdiv 3.7.0.
//!
//! The data lives in `tests/data/upstream/` and is generated by
//! `tools/osd_reference/generate.sh` (see the README there). For each shape
//! it holds the base mesh (`<shape>.mesh`) and OpenSubdiv's results
//! (`<shape>.ref`):
//!
//! * uniform refinement: per-level vertex/edge/face counts, and a sample of
//!   last-level face corners with their refined position, limit position,
//!   UV and UV limit;
//! * adaptive patch tables (isolation 4, isolation 4 with single-crease
//!   patches, isolation 3 with face-varying patches; Gregory-basis end caps,
//!   `useInfSharpPatch` on): patch counts per type, and a sample of patch
//!   evaluations (position, du, dv, and UV).
//!
//! Refined components are numbered differently in this crate, so corners
//! are matched by position, not by index.
//!
//! Every known difference from OpenSubdiv is listed in [`KNOWN_DEVIATIONS`]
//! with the issue that tracks it. The test fails on any difference that is
//! not listed, and also on a listed difference that no longer occurs, so a
//! fix has to remove its entry.

use opensubdiv_rs::far::{
    AdaptiveOptions, FVarChannelDescriptor, PatchMap, PatchTableFactory, PatchTableOptions,
    PatchType, PrimvarRefiner, TopologyDescriptor, TopologyRefiner, TopologyRefinerFactory,
    UniformOptions,
};
use opensubdiv_rs::sdc::{
    self, CreasingMethod, FVarLinearInterpolation, SchemeType, TriangleSubdivision,
    VtxBoundaryInterpolation,
};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Mutex;

/// What is compared, per shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Check {
    /// `TopologyRefinerFactory::create` accepts the mesh.
    Create,
    /// Vertex, edge and face counts of every uniform level.
    UniformCounts,
    /// Refined positions at the last uniform level.
    UniformPositions,
    /// `PrimvarRefiner::limit` at the last uniform level.
    UniformLimit,
    /// Refined UVs at the last uniform level.
    UniformFVar,
    /// `PrimvarRefiner::limit_face_varying` at the last uniform level.
    UniformFVarLimit,
    /// Number of patches of each type.
    PatchCounts(Config),
    /// Patch positions; also whether a patch is found at all.
    PatchPositions(Config),
    /// First derivatives on B-spline and box-spline patches.
    PatchDerivatives(Config),
    /// Face-varying patch values.
    FVarPatches(Config),
}

/// The adaptive configurations of the reference data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Config {
    /// Isolation 4.
    Iso4,
    /// Isolation 4 with single-crease patches.
    Iso4SingleCrease,
    /// Isolation 3 with face-varying patches.
    Iso3FVar,
}

use Check::*;
use Config::*;

/// Known differences from OpenSubdiv 3.7.0: (shape, check, cause).
///
/// The cause is an issue number
/// (<https://github.com/doubleailes/OpenSubdiv-rs/issues>), a documented
/// deviation, or "undiagnosed":
///
/// * #32: Chaikin creasing averages infinitely sharp neighbour edges.
/// * #34: the Catmark limit mask at valence-2 vertices.
/// * #35: faces with a repeated vertex are rejected.
/// * #36: vertices used by no face are dropped from refined levels.
/// * #37: distinct edges between the same two vertices are merged.
/// * #39: `VtxBoundaryInterpolation::None` keeps the boundary faces.
/// * #40: smooth corners get Gregory caps (no legacy sharp-corner patches).
/// * #41: Gregory caps where unresolved semi-sharp creases leave the
///   topology regular.
/// * #43, #46: a different patch layout (sparse levels, isolation around
///   infinitely sharp and non-manifold features); same surface.
/// * single-crease: the documented single-crease deviation (README): this
///   crate evaluates the authored crease sharpness, OpenSubdiv caps it at
///   the remaining isolation levels.
/// * undiagnosed: refined positions differ and no issue explains it yet.
#[rustfmt::skip]
const KNOWN_DEVIATIONS: &[(&str, Check, &str)] = &[
    ("catmark_cube_creases1", PatchCounts(Iso4), "#41"),
    ("catmark_cube_creases1", PatchCounts(Iso3FVar), "#41"),
    ("catmark_cube_creases1", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_cube_creases1", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_cube_creases2", PatchCounts(Iso4), "#43 #46"),
    ("catmark_cube_creases2", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_cube_creases2", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_cubes_infsharp", PatchCounts(Iso4), "#43 #46"),
    ("catmark_cubes_infsharp", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_cubes_infsharp", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_cubes_semisharp", PatchCounts(Iso4), "#41"),
    ("catmark_cubes_semisharp", PatchCounts(Iso3FVar), "#41"),
    ("catmark_cubes_semisharp", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_cubes_semisharp", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_chaikin0", PatchCounts(Iso4), "#41"),
    ("catmark_chaikin0", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_chaikin0", PatchCounts(Iso3FVar), "#41"),
    ("catmark_chaikin0", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_chaikin0", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_chaikin1", PatchCounts(Iso4), "#41"),
    ("catmark_chaikin1", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_chaikin1", PatchCounts(Iso3FVar), "#41"),
    ("catmark_chaikin2", UniformPositions, "#32"),
    ("catmark_chaikin2", UniformLimit, "#32"),
    ("catmark_chaikin2", PatchCounts(Iso4), "#32"),
    ("catmark_chaikin2", PatchCounts(Iso4SingleCrease), "#32"),
    ("catmark_chaikin2", PatchCounts(Iso3FVar), "#32"),
    ("catmark_chaikin2", PatchPositions(Iso4), "#32"),
    ("catmark_chaikin2", PatchPositions(Iso4SingleCrease), "#32"),
    ("catmark_chaikin2", PatchPositions(Iso3FVar), "#32"),
    ("catmark_chaikin2", PatchDerivatives(Iso4), "#32"),
    ("catmark_chaikin2", PatchDerivatives(Iso4SingleCrease), "#32"),
    ("catmark_chaikin2", PatchDerivatives(Iso3FVar), "#32"),
    ("catmark_dart_edgecorner", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_dart_edgecorner", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_dart_edgeonly", PatchCounts(Iso4), "#40 #41"),
    ("catmark_dart_edgeonly", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_dart_edgeonly", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_dart_edgeonly", PatchPositions(Iso4), "#40"),
    ("catmark_dart_edgeonly", PatchPositions(Iso4SingleCrease), "single-crease #40"),
    ("catmark_dart_edgeonly", PatchPositions(Iso3FVar), "#40"),
    ("catmark_dart_edgeonly", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_edgeonly", PatchCounts(Iso4), "#40 #41"),
    ("catmark_edgeonly", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_edgeonly", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_edgeonly", PatchPositions(Iso4), "#40"),
    ("catmark_edgeonly", PatchPositions(Iso4SingleCrease), "single-crease #40"),
    ("catmark_edgeonly", PatchPositions(Iso3FVar), "#40"),
    ("catmark_edgenone", UniformPositions, "#39"),
    ("catmark_edgenone", UniformLimit, "#39"),
    ("catmark_edgenone", UniformFVar, "#39"),
    ("catmark_edgenone", UniformFVarLimit, "#39"),
    ("catmark_edgenone", PatchCounts(Iso4), "#39"),
    ("catmark_edgenone", PatchCounts(Iso4SingleCrease), "#39"),
    ("catmark_edgenone", PatchCounts(Iso3FVar), "#39"),
    ("catmark_edgenone", PatchPositions(Iso4), "#39"),
    ("catmark_edgenone", PatchPositions(Iso4SingleCrease), "#39"),
    ("catmark_edgenone", PatchPositions(Iso3FVar), "#39"),
    ("catmark_fan", PatchCounts(Iso4), "#43 #46"),
    ("catmark_fan", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_fan", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_flap", PatchCounts(Iso4), "#40"),
    ("catmark_flap", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_flap", PatchCounts(Iso3FVar), "#40"),
    ("catmark_flap", PatchPositions(Iso4), "#40"),
    ("catmark_flap", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_flap", PatchPositions(Iso3FVar), "#40"),
    ("catmark_flap2", PatchCounts(Iso4), "#40"),
    ("catmark_flap2", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_flap2", PatchCounts(Iso3FVar), "#40"),
    ("catmark_flap2", PatchPositions(Iso4), "#40"),
    ("catmark_flap2", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_flap2", PatchPositions(Iso3FVar), "#40"),
    ("catmark_fvar_bound0", PatchCounts(Iso4), "#40"),
    ("catmark_fvar_bound0", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_fvar_bound0", PatchCounts(Iso3FVar), "#40"),
    ("catmark_fvar_bound0", PatchPositions(Iso4), "#40"),
    ("catmark_fvar_bound0", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_fvar_bound0", PatchPositions(Iso3FVar), "#40"),
    ("catmark_fvar_bound1", PatchCounts(Iso4), "#40"),
    ("catmark_fvar_bound1", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_fvar_bound1", PatchCounts(Iso3FVar), "#40"),
    ("catmark_fvar_bound1", PatchPositions(Iso4), "#40"),
    ("catmark_fvar_bound1", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_fvar_bound1", PatchPositions(Iso3FVar), "#40"),
    ("catmark_fvar_bound2", PatchCounts(Iso4), "#40 #41"),
    ("catmark_fvar_bound2", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_fvar_bound2", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_fvar_bound2", PatchPositions(Iso4), "#40"),
    ("catmark_fvar_bound2", PatchPositions(Iso4SingleCrease), "single-crease #40"),
    ("catmark_fvar_bound2", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test0", PatchCounts(Iso4), "#40"),
    ("catmark_gregory_test0", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test0", PatchCounts(Iso3FVar), "#40"),
    ("catmark_gregory_test0", PatchPositions(Iso4), "#40"),
    ("catmark_gregory_test0", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test0", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test2", PatchCounts(Iso4), "#40"),
    ("catmark_gregory_test2", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test2", PatchCounts(Iso3FVar), "#40"),
    ("catmark_gregory_test2", PatchPositions(Iso4), "#40"),
    ("catmark_gregory_test2", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test2", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test3", PatchCounts(Iso4), "#40 #41"),
    ("catmark_gregory_test3", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_gregory_test3", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_gregory_test3", PatchPositions(Iso4), "#40"),
    ("catmark_gregory_test3", PatchPositions(Iso4SingleCrease), "single-crease #40"),
    ("catmark_gregory_test3", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test4", PatchCounts(Iso4), "#43 #46"),
    ("catmark_gregory_test4", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_gregory_test4", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_gregory_test5", PatchCounts(Iso4), "#40"),
    ("catmark_gregory_test5", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test5", PatchCounts(Iso3FVar), "#40"),
    ("catmark_gregory_test6", PatchCounts(Iso4), "#40"),
    ("catmark_gregory_test6", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test6", PatchCounts(Iso3FVar), "#40"),
    ("catmark_gregory_test6", PatchPositions(Iso4), "#40"),
    ("catmark_gregory_test6", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_gregory_test6", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test7", PatchCounts(Iso4), "#40 #41"),
    ("catmark_gregory_test7", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_gregory_test7", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_gregory_test7", PatchPositions(Iso4), "#40"),
    ("catmark_gregory_test7", PatchPositions(Iso4SingleCrease), "single-crease #40"),
    ("catmark_gregory_test7", PatchPositions(Iso3FVar), "#40"),
    ("catmark_gregory_test7", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_gregory_test8", UniformLimit, "#34"),
    ("catmark_helmet", PatchCounts(Iso4), "#41"),
    ("catmark_helmet", PatchCounts(Iso3FVar), "#41"),
    ("catmark_helmet", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_helmet", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_hole_test2", PatchCounts(Iso4), "#41"),
    ("catmark_hole_test2", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_hole_test2", PatchCounts(Iso3FVar), "#41"),
    ("catmark_hole_test4", PatchCounts(Iso4), "#40"),
    ("catmark_hole_test4", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_hole_test4", PatchCounts(Iso3FVar), "#40"),
    ("catmark_hole_test4", PatchPositions(Iso4), "#40"),
    ("catmark_hole_test4", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_hole_test4", PatchPositions(Iso3FVar), "#40"),
    ("catmark_nonman_edges", Create, "#35"),
    ("catmark_nonman_edge100", PatchCounts(Iso4), "#43 #46"),
    ("catmark_nonman_edge100", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_nonman_edge100", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_nonman_verts", UniformCounts, "#36"),
    ("catmark_nonman_verts", PatchCounts(Iso4), "#43 #46"),
    ("catmark_nonman_verts", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_nonman_verts", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_nonman_quadpole8", Create, "#35"),
    ("catmark_nonman_quadpole64", Create, "#35"),
    ("catmark_nonman_quadpole360", Create, "#35"),
    ("catmark_nonman_bareverts", UniformCounts, "#36"),
    ("catmark_nonman_bareverts", PatchCounts(Iso4), "#40"),
    ("catmark_nonman_bareverts", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_nonman_bareverts", PatchCounts(Iso3FVar), "#40"),
    ("catmark_nonman_bareverts", PatchPositions(Iso4), "#40"),
    ("catmark_nonman_bareverts", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_nonman_bareverts", PatchPositions(Iso3FVar), "#40"),
    ("catmark_nonman_creases", PatchCounts(Iso4), "#43 #46"),
    ("catmark_nonman_creases", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_nonman_creases", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_pawn", PatchCounts(Iso4), "#41"),
    ("catmark_pawn", PatchCounts(Iso3FVar), "#41"),
    ("catmark_pawn", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases0", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases0", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases1", PatchCounts(Iso3FVar), "#41"),
    ("catmark_pyramid_creases1", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases1", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases2", PatchCounts(Iso3FVar), "#41"),
    ("catmark_pyramid_creases2", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_pyramid_creases2", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_single_crease", PatchCounts(Iso4), "#40 #41"),
    ("catmark_single_crease", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_single_crease", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_single_crease", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_single_crease", PatchPositions(Iso3FVar), "#40"),
    ("catmark_single_crease", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_inf_crease0", PatchCounts(Iso4), "#43 #46"),
    ("catmark_inf_crease0", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_inf_crease0", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_inf_crease1", PatchCounts(Iso4), "#43 #46"),
    ("catmark_inf_crease1", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("catmark_inf_crease1", PatchCounts(Iso3FVar), "#43 #46"),
    ("catmark_tent_creases0", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_tent_creases0", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_tent", PatchCounts(Iso4), "#40"),
    ("catmark_tent", PatchCounts(Iso4SingleCrease), "#40"),
    ("catmark_tent", PatchCounts(Iso3FVar), "#40"),
    ("catmark_tent", PatchPositions(Iso4), "#40"),
    ("catmark_tent", PatchPositions(Iso4SingleCrease), "#40"),
    ("catmark_tent", PatchPositions(Iso3FVar), "#40"),
    ("catmark_torus_creases0", PatchCounts(Iso4), "#41"),
    ("catmark_torus_creases0", PatchCounts(Iso3FVar), "#41"),
    ("catmark_torus_creases1", PatchCounts(Iso4), "#41"),
    ("catmark_torus_creases1", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_torus_creases1", PatchCounts(Iso3FVar), "#41"),
    ("catmark_val2_interior", PatchCounts(Iso4), "#41"),
    ("catmark_val2_interior", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_val2_interior", PatchCounts(Iso3FVar), "#41"),
    ("catmark_val2_interior", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_val2_interior", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_val2_back2back", UniformLimit, "#34"),
    ("catmark_val2_foldover", UniformLimit, "#34"),
    ("catmark_val2_nonman", UniformCounts, "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", UniformPositions, "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", UniformLimit, "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", UniformFVar, "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", UniformFVarLimit, "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchCounts(Iso4), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchCounts(Iso4SingleCrease), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchCounts(Iso3FVar), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchPositions(Iso4), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchPositions(Iso4SingleCrease), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchPositions(Iso3FVar), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchDerivatives(Iso4), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchDerivatives(Iso4SingleCrease), "#34 #36 undiagnosed"),
    ("catmark_val2_nonman", PatchDerivatives(Iso3FVar), "#34 #36 undiagnosed"),
    ("loop_chaikin0", PatchCounts(Iso4), "#41"),
    ("loop_chaikin0", PatchCounts(Iso4SingleCrease), "#41"),
    ("loop_chaikin0", PatchCounts(Iso3FVar), "#41"),
    ("loop_chaikin1", PatchCounts(Iso4), "#41"),
    ("loop_chaikin1", PatchCounts(Iso4SingleCrease), "#41"),
    ("loop_chaikin1", PatchCounts(Iso3FVar), "#41"),
    ("loop_cube_creases1", PatchCounts(Iso4), "#41"),
    ("loop_cube_creases1", PatchCounts(Iso4SingleCrease), "#41"),
    ("loop_cube_creases1", PatchCounts(Iso3FVar), "#41"),
    ("loop_cubes_semisharp", PatchCounts(Iso4), "#41"),
    ("loop_cubes_semisharp", PatchCounts(Iso4SingleCrease), "#41"),
    ("loop_cubes_semisharp", PatchCounts(Iso3FVar), "#41"),
    ("loop_icos_infsharp", PatchCounts(Iso4), "#43 #46"),
    ("loop_icos_infsharp", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("loop_icos_infsharp", PatchCounts(Iso3FVar), "#43 #46"),
    ("loop_icos_semisharp", PatchCounts(Iso4), "#41"),
    ("loop_icos_semisharp", PatchCounts(Iso4SingleCrease), "#41"),
    ("loop_icos_semisharp", PatchCounts(Iso3FVar), "#41"),
    ("loop_nonman_edges", Create, "#35"),
    ("loop_nonman_edge100", PatchCounts(Iso4), "#43 #46"),
    ("loop_nonman_edge100", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("loop_nonman_edge100", PatchCounts(Iso3FVar), "#43 #46"),
    ("loop_nonman_verts", UniformCounts, "#36"),
    ("loop_nonman_verts", PatchCounts(Iso4), "#43 #46"),
    ("loop_nonman_verts", PatchCounts(Iso4SingleCrease), "#43 #46"),
    ("loop_nonman_verts", PatchCounts(Iso3FVar), "#43 #46"),
    ("loop_saddle_edgeonly", PatchCounts(Iso4), "#40"),
    ("loop_saddle_edgeonly", PatchCounts(Iso4SingleCrease), "#40"),
    ("loop_saddle_edgeonly", PatchCounts(Iso3FVar), "#40"),
    ("loop_saddle_edgeonly", PatchPositions(Iso4), "#40"),
    ("loop_saddle_edgeonly", PatchPositions(Iso4SingleCrease), "#40"),
    ("loop_saddle_edgeonly", PatchPositions(Iso3FVar), "#40"),
    ("loop_triangle_edgeonly", PatchCounts(Iso4), "#40 #41"),
    ("loop_triangle_edgeonly", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("loop_triangle_edgeonly", PatchCounts(Iso3FVar), "#40 #41"),
    ("loop_val2_interior", UniformCounts, "#37"),
    ("loop_val2_interior", UniformPositions, "#37"),
    ("loop_val2_interior", UniformLimit, "#37"),
    ("loop_val2_interior", UniformFVar, "#37"),
    ("loop_val2_interior", UniformFVarLimit, "#37"),
    ("loop_val2_interior", PatchCounts(Iso4), "#37"),
    ("loop_val2_interior", PatchCounts(Iso4SingleCrease), "#37"),
    ("loop_val2_interior", PatchCounts(Iso3FVar), "#37"),
    ("loop_val2_interior", PatchPositions(Iso4), "#37"),
    ("loop_val2_interior", PatchPositions(Iso4SingleCrease), "#37"),
    ("loop_val2_interior", PatchPositions(Iso3FVar), "#37"),
    ("catmark_car", PatchCounts(Iso4), "#40 #41"),
    ("catmark_car", PatchCounts(Iso4SingleCrease), "#40 #41"),
    ("catmark_car", PatchCounts(Iso3FVar), "#40 #41"),
    ("catmark_car", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_rook", PatchCounts(Iso4), "#41"),
    ("catmark_rook", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_rook", PatchCounts(Iso3FVar), "#41"),
    ("catmark_rook", PatchDerivatives(Iso4SingleCrease), "single-crease"),
    ("catmark_bishop", PatchCounts(Iso4), "#41"),
    ("catmark_bishop", PatchCounts(Iso4SingleCrease), "#41"),
    ("catmark_bishop", PatchCounts(Iso3FVar), "#41"),
    ("catmark_bishop", PatchPositions(Iso4SingleCrease), "single-crease"),
    ("catmark_bishop", PatchDerivatives(Iso4SingleCrease), "single-crease"),
];

// ---------------------------------------------------------------------------
//  Data files
// ---------------------------------------------------------------------------

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data/upstream")
}

struct Tokens<'a>(std::str::SplitWhitespace<'a>);

impl<'a> Tokens<'a> {
    fn new(text: &'a str) -> Self {
        Tokens(text.split_whitespace())
    }
    fn word(&mut self) -> &'a str {
        self.0.next().expect("unexpected end of reference data")
    }
    fn int(&mut self) -> usize {
        self.word().parse().expect("integer")
    }
    fn real(&mut self) -> f64 {
        self.word().parse().expect("number")
    }
    fn reals<const N: usize>(&mut self) -> [f64; N] {
        std::array::from_fn(|_| self.real())
    }
    fn keyword(&mut self, expected: &str) {
        let word = self.word();
        assert_eq!(word, expected, "malformed reference data");
    }
}

struct Mesh {
    scheme: SchemeType,
    options: sdc::Options,
    positions: Vec<[f64; 3]>,
    verts_per_face: Vec<usize>,
    face_verts: Vec<u32>,
    creases: Vec<[u32; 2]>,
    crease_weights: Vec<f32>,
    corners: Vec<u32>,
    corner_weights: Vec<f32>,
    holes: Vec<u32>,
    uvs: Vec<[f64; 2]>,
    face_uvs: Vec<u32>,
}

impl Mesh {
    fn parse(text: &str) -> Mesh {
        let mut t = Tokens::new(text);
        t.keyword("scheme");
        let scheme = match t.int() {
            0 => SchemeType::Bilinear,
            1 => SchemeType::Catmark,
            _ => SchemeType::Loop,
        };
        t.keyword("options");
        let boundary = match t.int() {
            0 => VtxBoundaryInterpolation::None,
            1 => VtxBoundaryInterpolation::EdgeOnly,
            _ => VtxBoundaryInterpolation::EdgeAndCorner,
        };
        let fvar = match t.int() {
            0 => FVarLinearInterpolation::None,
            1 => FVarLinearInterpolation::CornersOnly,
            2 => FVarLinearInterpolation::CornersPlus1,
            3 => FVarLinearInterpolation::CornersPlus2,
            4 => FVarLinearInterpolation::Boundaries,
            _ => FVarLinearInterpolation::All,
        };
        let creasing = match t.int() {
            0 => CreasingMethod::Uniform,
            _ => CreasingMethod::Chaikin,
        };
        let triangles = match t.int() {
            0 => TriangleSubdivision::Catmark,
            _ => TriangleSubdivision::Smooth,
        };
        let options = sdc::Options::new()
            .with_vtx_boundary_interpolation(boundary)
            .with_fvar_linear_interpolation(fvar)
            .with_creasing_method(creasing)
            .with_triangle_subdivision(triangles);

        t.keyword("verts");
        let positions = (0..t.int()).map(|_| t.reals()).collect();
        t.keyword("faces");
        let mut verts_per_face = Vec::new();
        let mut face_verts = Vec::new();
        for _ in 0..t.int() {
            let n = t.int();
            verts_per_face.push(n);
            face_verts.extend((0..n).map(|_| t.int() as u32));
        }
        t.keyword("creases");
        let mut creases = Vec::new();
        let mut crease_weights = Vec::new();
        for _ in 0..t.int() {
            creases.push([t.int() as u32, t.int() as u32]);
            crease_weights.push(t.real() as f32);
        }
        t.keyword("corners");
        let mut corners = Vec::new();
        let mut corner_weights = Vec::new();
        for _ in 0..t.int() {
            corners.push(t.int() as u32);
            corner_weights.push(t.real() as f32);
        }
        t.keyword("holes");
        let holes = (0..t.int()).map(|_| t.int() as u32).collect();
        t.keyword("fvar");
        let uvs: Vec<[f64; 2]> = (0..t.int()).map(|_| t.reals()).collect();
        let face_uvs = if uvs.is_empty() {
            Vec::new()
        } else {
            (0..face_verts.len()).map(|_| t.int() as u32).collect()
        };
        Mesh {
            scheme,
            options,
            positions,
            verts_per_face,
            face_verts,
            creases,
            crease_weights,
            corners,
            corner_weights,
            holes,
            uvs,
            face_uvs,
        }
    }

    fn has_uvs(&self) -> bool {
        !self.uvs.is_empty()
    }

    fn refiner(&self) -> Result<TopologyRefiner, String> {
        let channels = [FVarChannelDescriptor::new(self.uvs.len(), &self.face_uvs)];
        let mut descriptor =
            TopologyDescriptor::new(self.positions.len(), &self.verts_per_face, &self.face_verts)
                .with_creases(&self.creases, &self.crease_weights)
                .with_corners(&self.corners, &self.corner_weights)
                .with_holes(&self.holes);
        if self.has_uvs() {
            descriptor = descriptor.with_fvar_channels(&channels);
        }
        TopologyRefinerFactory::create(descriptor, self.scheme, self.options)
            .map_err(|e| format!("{e:?}"))
    }

    /// Length of the bounding-box diagonal: the scale of position tolerances.
    fn size(&self) -> f64 {
        let mut lo = [f64::MAX; 3];
        let mut hi = [f64::MIN; 3];
        for p in &self.positions {
            for k in 0..3 {
                lo[k] = lo[k].min(p[k]);
                hi[k] = hi[k].max(p[k]);
            }
        }
        dist(&lo, &hi).max(1e-9)
    }
}

fn dist<const N: usize>(a: &[f64; N], b: &[f64; N]) -> f64 {
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y) * (x - y))
        .sum::<f64>()
        .sqrt()
}

fn norm<const N: usize>(a: &[f64; N]) -> f64 {
    dist(a, &[0.0; N])
}

fn patch_type_name(t: PatchType) -> &'static str {
    match t {
        PatchType::Regular => "REGULAR",
        PatchType::GregoryBasis => "GREGORY_BASIS",
        PatchType::Quads => "QUADS",
        PatchType::Loop => "LOOP",
        PatchType::GregoryTriangle => "GREGORY_TRIANGLE",
        PatchType::Triangles => "TRIANGLES",
    }
}

// ---------------------------------------------------------------------------
//  Comparison
// ---------------------------------------------------------------------------

/// Largest error and number of failures of one check.
#[derive(Default)]
struct Tally {
    max: f64,
    failed: usize,
    total: usize,
}

impl Tally {
    fn add(&mut self, error: f64, tolerance: f64) {
        self.total += 1;
        self.max = self.max.max(error);
        if error > tolerance || error.is_nan() {
            self.failed += 1;
        }
    }
}

/// The differences found on one shape: check → description.
type Findings = BTreeMap<Check, String>;

fn record(findings: &mut Findings, check: Check, tally: &Tally) {
    if tally.failed > 0 {
        findings.insert(
            check,
            format!(
                "{} of {} samples differ (max error {:.2e})",
                tally.failed, tally.total, tally.max
            ),
        );
    }
}

/// Position tolerance, relative to the mesh size. The reference values are
/// single precision with 7 significant digits.
const POSITION_TOLERANCE: f64 = 1e-4;
/// UV tolerance (UVs are within the unit square).
const UV_TOLERANCE: f64 = 1e-4;
/// Derivative tolerance, relative to the derivative's magnitude.
const DERIVATIVE_TOLERANCE: f64 = 1e-3;
/// Gregory triangles use this crate's own coefficients (README, Fidelity
/// notes): positions are only required to agree within this fraction of
/// the mesh size.
const GREGORY_TRIANGLE_TOLERANCE: f64 = 2e-2;

fn compare_shape(mesh: &Mesh, reference: &str) -> Findings {
    let mut findings = Findings::new();
    let size = mesh.size();
    let mut t = Tokens::new(reference);

    // ---- uniform refinement
    t.keyword("uniform");
    let level = t.int();
    let has_uvs = t.int() == 1;
    let mut refiner = match mesh.refiner() {
        Ok(refiner) => refiner,
        Err(e) => {
            findings.insert(Create, e);
            return findings;
        }
    };
    refiner.refine_uniform(UniformOptions::new(level));

    let mut counts = String::new();
    for l in 0..=level {
        t.keyword("level");
        t.int();
        let expected = (t.int(), t.int(), t.int());
        let lv = refiner.level(l);
        let actual = (lv.num_vertices(), lv.num_edges(), lv.num_faces());
        if expected != actual {
            let _ = write!(
                counts,
                "level {l}: (verts, edges, faces) {expected:?} in OpenSubdiv, {actual:?} here; "
            );
        }
    }
    if !counts.is_empty() {
        findings.insert(UniformCounts, counts);
    }

    let primvars = PrimvarRefiner::new(&refiner);
    let mut points = mesh.positions.clone();
    let mut uvs = mesh.uvs.clone();
    for l in 1..=level {
        let mut next = vec![[0.0; 3]; refiner.level(l).num_vertices()];
        primvars.interpolate(l, &points, &mut next);
        points = next;
        if has_uvs {
            let mut next = vec![[0.0; 2]; refiner.level(l).num_fvar_values(0)];
            primvars.interpolate_face_varying(l, 0, &uvs, &mut next);
            uvs = next;
        }
    }
    let mut limit = points.clone();
    primvars.limit(&points, &mut limit);
    let mut uv_limit = uvs.clone();
    if has_uvs {
        primvars.limit_face_varying(0, &uvs, &mut uv_limit);
    }

    // Index the last level's vertices by position.
    let lv = refiner.level(level);
    let cell = 1e-3 * size;
    let key = |p: &[f64; 3]| p.map(|x| (x / cell).floor() as i64);
    let mut grid: HashMap<[i64; 3], Vec<usize>> = HashMap::new();
    for (v, p) in points.iter().enumerate() {
        grid.entry(key(p)).or_default().push(v);
    }

    t.keyword("corners");
    let mut refined = Tally::default();
    let mut limits = Tally::default();
    let mut fvar = Tally::default();
    let mut fvar_limit = Tally::default();
    for _ in 0..t.int() {
        let p: [f64; 3] = t.reals();
        let l: [f64; 3] = t.reals();
        let uv: Option<([f64; 2], [f64; 2])> = has_uvs.then(|| (t.reals(), t.reals()));
        // Several vertices can share a position (the face points of
        // back-to-back faces, say): among the vertices within the tolerance
        // of the reference position, pick the one whose UV, then limit,
        // agrees best. Errors: (position, uv, limit, uv limit).
        let errors = |v: usize| -> [f64; 4] {
            let mut uv_errors = [0.0, 0.0];
            if let Some((uv, uv_lim)) = uv {
                // The vertex's face-varying value closest to the reference.
                uv_errors = [f64::INFINITY; 2];
                for &f in lv.vertex_faces(v) {
                    let f = f as usize;
                    for (corner, &fv) in lv.face_vertices(f).iter().enumerate() {
                        if fv as usize == v {
                            let value = lv.face_fvar_values(f, 0)[corner] as usize;
                            let e = [dist(&uvs[value], &uv), dist(&uv_limit[value], &uv_lim)];
                            if (e[0].max(UV_TOLERANCE), e[1])
                                < (uv_errors[0].max(UV_TOLERANCE), uv_errors[1])
                            {
                                uv_errors = e;
                            }
                        }
                    }
                }
            }
            [
                dist(&points[v], &p),
                uv_errors[0],
                dist(&limit[v], &l),
                uv_errors[1],
            ]
        };
        let rank = |e: &[f64; 4]| {
            (
                e[0].max(POSITION_TOLERANCE * size),
                e[1].max(UV_TOLERANCE),
                e[2],
                e[3],
            )
        };
        let k = key(&p);
        let mut best: Option<[f64; 4]> = None;
        for dx in -1..=1 {
            for dy in -1..=1 {
                for dz in -1..=1 {
                    for &v in grid
                        .get(&[k[0] + dx, k[1] + dy, k[2] + dz])
                        .into_iter()
                        .flatten()
                    {
                        let e = errors(v);
                        if best.is_none_or(|b| rank(&e) < rank(&b)) {
                            best = Some(e);
                        }
                    }
                }
            }
        }
        let [position, uv_error, limit_error, uv_limit_error] = best.unwrap_or([f64::INFINITY; 4]);
        refined.add(position, POSITION_TOLERANCE * size);
        limits.add(limit_error, POSITION_TOLERANCE * size);
        if uv.is_some() {
            fvar.add(uv_error, UV_TOLERANCE);
            fvar_limit.add(uv_limit_error, UV_TOLERANCE);
        }
    }
    record(&mut findings, UniformPositions, &refined);
    record(&mut findings, UniformLimit, &limits);
    record(&mut findings, UniformFVar, &fvar);
    record(&mut findings, UniformFVarLimit, &fvar_limit);

    // ---- adaptive patch tables
    while let Some(word) = t.0.next() {
        assert_eq!(word, "adaptive", "malformed reference data");
        let isolation = t.int();
        let single_crease = t.int() == 1;
        let face_varying = t.int() == 1;
        let config = match (isolation, single_crease) {
            (4, false) => Iso4,
            (4, true) => Iso4SingleCrease,
            _ => Iso3FVar,
        };
        compare_patches(
            mesh,
            &mut t,
            config,
            isolation,
            single_crease,
            face_varying,
            &mut findings,
        );
    }
    findings
}

fn compare_patches(
    mesh: &Mesh,
    t: &mut Tokens,
    config: Config,
    isolation: usize,
    single_crease: bool,
    face_varying: bool,
    findings: &mut Findings,
) {
    let size = mesh.size();
    t.keyword("patchcounts");
    let mut expected_counts = BTreeMap::new();
    for _ in 0..t.int() {
        let name = t.word();
        expected_counts.insert(name, t.int());
    }

    let mut refiner = mesh.refiner().expect("accepted for uniform refinement");
    refiner
        .refine_adaptive(AdaptiveOptions::new(isolation).with_single_crease_patch(single_crease));
    let options = PatchTableOptions::new()
        .with_fvar_tables(face_varying)
        .with_fvar_legacy_linear_patches(false);
    let table = PatchTableFactory::create_with_options(&refiner, &options);

    t.keyword("samples");
    let samples = t.int();
    let table = match table {
        Ok(table) => table,
        Err(e) => {
            findings.insert(PatchCounts(config), format!("no patch table: {e:?}"));
            for _ in 0..samples {
                t.int();
                t.real();
                t.real();
                if t.word() != "none" {
                    for _ in 0..(10 + if face_varying { 6 } else { 0 }) {
                        t.word();
                    }
                }
            }
            return;
        }
    };

    let mut counts = BTreeMap::new();
    for patch in 0..table.num_patches() {
        *counts
            .entry(patch_type_name(table.patch_type(patch)))
            .or_insert(0) += 1;
    }
    if counts != expected_counts {
        findings.insert(
            PatchCounts(config),
            format!("{expected_counts:?} in OpenSubdiv, {counts:?} here"),
        );
    }

    let primvars = PrimvarRefiner::new(&refiner);
    let mut points = mesh.positions.clone();
    points.extend(primvars.interpolate_all(&mesh.positions).concat());
    let mut uvs = mesh.uvs.clone();
    if face_varying {
        uvs.extend(primvars.interpolate_face_varying_all(0, &mesh.uvs).concat());
    }
    let map = PatchMap::new(&table);
    let (mut positions, mut derivatives, mut fvar) =
        (Tally::default(), Tally::default(), Tally::default());
    for _ in 0..samples {
        let face = t.int();
        let u = t.real() as f32;
        let v = t.real() as f32;
        let osd_type = t.word();
        let patch = map.find_patch(face, u, v);
        if osd_type == "none" {
            positions.add(if patch.is_some() { f64::INFINITY } else { 0.0 }, 0.0);
            continue;
        }
        let non_quad_root = t.int() == 1;
        let p: [f64; 3] = t.reals();
        let du: [f64; 3] = t.reals();
        let dv: [f64; 3] = t.reals();
        let fv: Option<[f64; 6]> = face_varying.then(|| t.reals());
        let Some(patch) = patch else {
            positions.add(f64::INFINITY, 0.0);
            continue;
        };

        let (rp, rdu, rdv) = table.evaluate(patch, u, v, &points);
        let tolerance = if osd_type == "GREGORY_TRIANGLE" {
            GREGORY_TRIANGLE_TOLERANCE
        } else {
            POSITION_TOLERANCE
        };
        positions.add(dist(&rp, &p), tolerance * size);

        // OpenSubdiv's derivatives on the sub-faces of non-quad faces are
        // twice the derivative in the sub-face's parameter (issue #45).
        // Gregory derivatives are approximate in OpenSubdiv: not compared.
        let rust_type = patch_type_name(table.patch_type(patch));
        if (osd_type == "REGULAR" || osd_type == "LOOP") && rust_type == osd_type {
            let scale = if non_quad_root { 0.5 } else { 1.0 };
            let du = du.map(|x| x * scale);
            let dv = dv.map(|x| x * scale);
            let magnitude = norm(&du).max(norm(&dv)).max(1e-3 * size);
            let error = dist(&rdu, &du).max(dist(&rdv, &dv)) / magnitude;
            derivatives.add(error, DERIVATIVE_TOLERANCE);
        }

        if let Some(fv) = fv {
            let (uv, _, _) = table.evaluate_face_varying(patch, u, v, &uvs, 0);
            let tolerance = if osd_type == "GREGORY_TRIANGLE" {
                GREGORY_TRIANGLE_TOLERANCE
            } else {
                UV_TOLERANCE
            };
            fvar.add(dist(&uv, &[fv[0], fv[1]]), tolerance);
        }
    }
    record(findings, PatchPositions(config), &positions);
    record(findings, PatchDerivatives(config), &derivatives);
    record(findings, FVarPatches(config), &fvar);
}

// ---------------------------------------------------------------------------
//  The test
// ---------------------------------------------------------------------------

#[test]
fn matches_opensubdiv_on_regression_shapes() {
    let dir = data_dir();
    let list = std::fs::read_to_string(dir.join("shapes.txt")).expect("tests/data/upstream");
    let known: BTreeSet<(&str, Check)> = KNOWN_DEVIATIONS.iter().map(|&(s, c, _)| (s, c)).collect();
    assert_eq!(
        known.len(),
        KNOWN_DEVIATIONS.len(),
        "duplicate known deviation"
    );

    // UPSTREAM_SHAPES=a,b restricts the run to those shapes.
    let only = std::env::var("UPSTREAM_SHAPES").ok();
    let names: Vec<&str> = list
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .filter(|name| {
            only.as_deref()
                .is_none_or(|o| o.split(',').any(|s| s == *name))
        })
        .collect();
    assert!(!names.is_empty(), "no shape selected");

    // The shapes are independent: compare them on all cores.
    let next = AtomicUsize::new(0);
    let results = Mutex::new(Vec::new());
    let threads = std::thread::available_parallelism().map_or(1, |n| n.get());
    std::thread::scope(|scope| {
        for _ in 0..threads.min(names.len()) {
            scope.spawn(|| loop {
                let i = next.fetch_add(1, Ordering::Relaxed);
                let Some(&name) = names.get(i) else { break };
                let read =
                    |ext: &str| std::fs::read_to_string(dir.join(format!("{name}.{ext}"))).unwrap();
                let mesh = Mesh::parse(&read("mesh"));
                let reference = read("ref");
                let findings = std::panic::catch_unwind(|| compare_shape(&mesh, &reference))
                    .unwrap_or_else(|_| Findings::from([(Create, "panicked".to_string())]));
                results.lock().unwrap().push((i, name, findings));
            });
        }
    });
    let mut results = results.into_inner().unwrap();
    results.sort_by_key(|&(i, _, _)| i);

    let mut unexpected = Vec::new();
    let mut fixed = Vec::new();
    for (_, name, findings) in &results {
        for (check, detail) in findings {
            if !known.contains(&(*name, *check)) {
                unexpected.push(format!("    (\"{name}\", {check:?}, \"\"), // {detail}"));
            }
        }
        for &(shape, check, why) in KNOWN_DEVIATIONS {
            // A failed Create skips every other check of the shape.
            let skipped = findings.contains_key(&Create) && check != Create;
            if shape == *name && !findings.contains_key(&check) && !skipped {
                fixed.push(format!("    (\"{shape}\", {check:?}, \"{why}\")"));
            }
        }
    }

    let mut message = String::new();
    if !unexpected.is_empty() {
        let _ = writeln!(
            message,
            "{} differences from OpenSubdiv are not in KNOWN_DEVIATIONS:\n{}",
            unexpected.len(),
            unexpected.join("\n")
        );
    }
    if !fixed.is_empty() {
        let _ = writeln!(
            message,
            "{} known deviations no longer occur; remove them from KNOWN_DEVIATIONS:\n{}",
            fixed.len(),
            fixed.join("\n")
        );
    }
    assert!(message.is_empty(), "{message}");
}
